name: GStreamer Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ gstreamer/** ]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Install GStreamer
        run: |
          choco install gstreamer;

      - name: Check PATH
        shell: powershell
        run: |
          Get-ChildItem env:;
          ${ENV:Path}.Split(';');

          # Setup and use the Chocolatey helpers
          Import-Module "${ENV:ChocolateyInstall}\helpers\chocolateyProfile.psm1";
          Update-SessionEnvironment;

          Get-ChildItem env:;
          ${ENV:Path}.Split(';');

          where.exe gst-launch-1.0;
          gst-launch-1.0 --version;
